### ISSUE TITLE
Federated cloud ID is missing from existing contacts and can't be added.

### ISSUE THREAD

**Issue by lachlan-00** [nextcloud/contacts#814]
In the web interface i am unable to add the Federated Cloud ID property. Nothing happens in Chrome or Firefox and the field is missing from contacts who previously had one.

Steps to reproduce the behaviour:
1. Go to Contacts
2. Click on existing contact or create a new one.
3. Click 'Choose property type'
4. Select 'Federated Cloud ID'
5. Nothing happens but it looks like it affect the email field in existing contacts.

### Server configuration

**Operating system**: Linux (Debian Testing)

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 15.0.0

**Contacts version:** 3.0.1

**Updated from an older Nextcloud**

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
root@web:~# bin/occ app:list                                                                            
Enabled:                                                                                                
  - accessibility: 1.1.0                                                                                
  - activity: 2.8.2                                                                                     
  - admin_audit: 1.5.0                                                                                  
  - bruteforcesettings: 1.3.0                                                                           
  - calendar: 1.6.4                                                                                     
  - cloud_federation_api: 0.1.0                                                                         
  - contacts: 3.0.1                                                                                     
  - dav: 1.8.0                                                                                          
  - federatedfilesharing: 1.5.0                                                                         
  - federation: 1.5.0                                                                                   
  - files: 1.10.0                                                                                       
  - files_downloadactivity: 1.4.0                                                                       
  - files_external: 1.6.0                                                                               
  - files_pdfviewer: 1.4.0                                                                              
  - files_sharing: 1.7.0                                                                                
  - files_texteditor: 2.7.0                                                                             
  - files_trashbin: 1.5.0                                                                               
  - files_versions: 1.8.0                                                                               
  - files_videoplayer: 1.4.0                                                                            
  - firstrunwizard: 2.4.0                                                                               
  - gallery: 18.2.0                                                                                     
  - logreader: 2.0.0                                                                                    
  - lookup_server_connector: 1.3.0                                                                      
  - mail: 0.11.0                                                                                        
  - news: 13.0.3                                                                                        
  - nextcloud_announcements: 1.4.0                                                                      
  - notes: 2.5.1                                                                                        
  - notifications: 2.3.0                                                                                
  - oauth2: 1.3.0                                                                                       
  - password_policy: 1.5.0                                                                              
  - passwords: 2019.1.0-build2622                                                                       
  - previewgenerator: 2.0.0                                                                             
  - provisioning_api: 1.5.0                                                                             
  - richdocuments: 3.1.0                                                                                
  - sharebymail: 1.5.0                                                                                  
  - social: 0.1.1                                                                                       
  - spreed: 5.0.0                                                                                       
  - survey_client: 1.3.0                                                                                
  - systemtags: 1.5.0                                                                                   
  - tasks: 0.9.8                                                                                        
  - theming: 1.6.0                                                                                      
  - twofactor_backupcodes: 1.4.1                                                                        
  - updatenotification: 1.5.0                                                                           
  - workflowengine: 1.5.0                                                                               
Disabled:                                                                                               
  - comments                                                                                            
```

**Nextcloud configuration:**
```
root@web:~# bin/occ config:list system                                                                  
{                                                                                                       
    "system": {                                                                                         
        "instanceid": "***REMOVED SENSITIVE VALUE***",                                                  
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",                                                
        "secret": "***REMOVED SENSITIVE VALUE***",                                                      
        "trusted_domains": [                                                                            
            "cloud.lachlandewaard.org",                                                                 
            "lnxt.cloud"                                                                                
        ],                                                                                              
        "htaccess.RewriteBase": "\/",                                                                   
        "datadirectory": "***REMOVED SENSITIVE VALUE***",                                               
        "dbtype": "mysql",                                                                              
        "version": "15.0.0.10",                                                                         
        "dbname": "***REMOVED SENSITIVE VALUE***",                                                      
        "dbhost": "***REMOVED SENSITIVE VALUE***",                                                      
        "dbport": "3306",                                                                               
```
